# Generated by Django 5.1.7 on 2025-03-06 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_id', models.IntegerField(blank=True, help_text='ID of the lead if created', null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('validated_at', models.DateTimeField(auto_now_add=True)),
                ('results', models.JSONField(blank=True, help_text='Full validation results', null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_quality_threshold', models.IntegerField(default=80, help_text='Minimum score for high quality leads')),
                ('medium_quality_threshold', models.IntegerField(default=50, help_text='Minimum score for medium quality leads')),
                ('email_weight', models.IntegerField(default=40, help_text='Maximum points for email validation')),
                ('phone_weight', models.IntegerField(default=30, help_text='Maximum points for phone validation')),
                ('location_weight', models.IntegerField(default=15, help_text='Maximum points for location validation')),
                ('name_weight', models.IntegerField(default=15, help_text='Maximum points for name validation')),
                ('disposable_domains', models.TextField(blank=True, help_text='Comma-separated list of disposable email domains to block')),
                ('reject_disposable_emails', models.BooleanField(default=True)),
                ('reject_invalid_phones', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
