# Generated by Django 5.1.7 on 2025-03-06 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('referral_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('insurance_type', models.CharField(choices=[('auto', 'Auto Insurance'), ('home', 'Home Insurance'), ('business', 'Business Insurance'), ('life', 'Life Insurance'), ('health', 'Health Insurance'), ('other', 'Other')], max_length=20)),
                ('vehicle_vin', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('vehicle_year', models.IntegerField(blank=True, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_usage', models.CharField(blank=True, max_length=20, null=True)),
                ('annual_mileage', models.IntegerField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('current_insurer', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=50, null=True)),
                ('ownership_status', models.CharField(blank=True, max_length=20, null=True)),
                ('year_built', models.IntegerField(blank=True, null=True)),
                ('square_footage', models.IntegerField(blank=True, null=True)),
                ('num_bedrooms', models.IntegerField(blank=True, null=True)),
                ('num_bathrooms', models.IntegerField(blank=True, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_address', models.CharField(blank=True, max_length=255, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('num_employees', models.IntegerField(blank=True, null=True)),
                ('annual_revenue', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('text', 'Text Message')], default='phone', max_length=20)),
                ('preferred_time', models.CharField(blank=True, choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('validation_score', models.IntegerField(default=0, help_text='Overall quality score (0-100)')),
                ('validation_details', models.JSONField(blank=True, help_text='Detailed validation results', null=True)),
                ('validation_timestamp', models.DateTimeField(blank=True, help_text='When validation was performed', null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('quoted', 'Quote Completed'), ('converted', 'Policy Purchased'), ('closed', 'Closed (No Sale)')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_sent', models.BooleanField(default=False)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('referral_link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='referral_system.referrallink')),
            ],
        ),
    ]
