# Generated by Django 5.1.6 on 2025-03-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_capture', '0002_lead_address_lead_annual_revenue_lead_business_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='annual_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='business_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='num_bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='num_bedrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='vehicle_usage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
