# Generated by Django 5.1.6 on 2025-03-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_capture', '0003_lead_annual_mileage_lead_business_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
