# Generated by Django 5.1.7 on 2025-03-08 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPaymentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_rate', models.DecimalField(decimal_places=2, default=25.0, help_text='Default payment rate when no specific rate applies', max_digits=10)),
                ('preferred_payment_method', models.CharField(choices=[('direct_deposit', 'Direct Deposit'), ('paypal', 'PayPal'), ('check', 'Check'), ('venmo', 'Venmo'), ('zelle', 'Zelle')], default='direct_deposit', max_length=20)),
                ('payment_email', models.EmailField(blank=True, help_text='Email address for PayPal, Venmo, etc.', max_length=254, null=True)),
                ('account_number', models.CharField(blank=True, help_text='Account number for direct deposit', max_length=255, null=True)),
                ('routing_number', models.CharField(blank=True, help_text='Routing number for direct deposit', max_length=255, null=True)),
                ('payment_schedule', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-weekly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('payment_threshold', models.DecimalField(decimal_places=2, default=50.0, help_text='Minimum amount before payment is issued', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('', 'Nationwide (Default Rate)'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], default='', max_length=2)),
                ('insurance_type', models.CharField(choices=[('auto', 'Auto Insurance'), ('home', 'Home Insurance'), ('business', 'Business Insurance'), ('life', 'Life Insurance'), ('health', 'Health Insurance'), ('other', 'Other')], default='auto', max_length=20)),
                ('rate_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('effective_from', models.DateField(auto_now_add=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('state', 'insurance_type')},
            },
        ),
        migrations.CreateModel(
            name='ReferralLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('visits', models.PositiveIntegerField(default=0)),
                ('conversions', models.PositiveIntegerField(default=0)),
                ('paid_conversions', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='My Referral Link', help_text='Name this link for your reference', max_length=100)),
                ('partner_name', models.CharField(blank=True, help_text='Business partner using this link', max_length=100, null=True)),
                ('insurance_type', models.CharField(choices=[('auto', 'Auto Insurance'), ('home', 'Home Insurance'), ('life', 'Life Insurance'), ('health', 'Health Insurance'), ('business', 'Business Insurance'), ('other', 'Other')], default='auto', max_length=50)),
                ('source', models.CharField(choices=[('website', 'Your Website'), ('email', 'Email Campaign'), ('social', 'Social Media'), ('partner', 'Business Partner'), ('print', 'Print Materials'), ('other', 'Other')], default='website', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('referral_type', models.CharField(choices=[('business', 'Business Partner'), ('customer', 'Existing Customer'), ('agent', 'Direct from Agent')], default='agent', help_text='Who is sharing this referral link', max_length=20)),
                ('customer_name', models.CharField(blank=True, help_text='Name of existing customer making the referral', max_length=100, null=True)),
                ('customer_email', models.EmailField(blank=True, help_text='Email of existing customer making the referral', max_length=254, null=True)),
                ('target_state', models.CharField(blank=True, choices=[('', 'Nationwide (Default Rate)'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], max_length=2, null=True)),
                ('earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_links', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AgentRateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, choices=[('', 'Nationwide (Default Rate)'), ('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], help_text='State this rate applies to (leave blank for all states)', max_length=2, null=True)),
                ('insurance_type', models.CharField(blank=True, choices=[('', 'All Insurance Types'), ('auto', 'Auto Insurance'), ('home', 'Home Insurance'), ('business', 'Business Insurance'), ('life', 'Life Insurance'), ('health', 'Health Insurance'), ('other', 'Other')], default='', help_text='Insurance type this rate applies to (leave blank for all types)', max_length=20)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Custom rate for this specific combination', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_overrides', to='referral_system.agentpaymentpreference')),
            ],
            options={
                'unique_together': {('preference', 'state', 'insurance_type')},
            },
        ),
    ]
