# Generated by Django 5.1.6 on 2025-03-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallink',
            name='insurance_type',
            field=models.CharField(choices=[('auto', 'Auto Insurance'), ('home', 'Home Insurance'), ('life', 'Life Insurance'), ('health', 'Health Insurance'), ('business', 'Business Insurance'), ('other', 'Other')], default='auto', max_length=50),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='name',
            field=models.CharField(default='My Referral Link', help_text='Name this link for your reference', max_length=100),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='partner_name',
            field=models.CharField(blank=True, help_text='Business partner using this link', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='source',
            field=models.CharField(choices=[('website', 'Your Website'), ('email', 'Email Campaign'), ('social', 'Social Media'), ('partner', 'Business Partner'), ('print', 'Print Materials'), ('other', 'Other')], default='website', max_length=50),
        ),
    ]
