# Generated by Django 5.1.6 on 2025-03-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0002_referrallink_insurance_type_referrallink_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallink',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Email of existing customer making the referral', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Name of existing customer making the referral', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='referral_type',
            field=models.CharField(choices=[('business', 'Business Partner'), ('customer', 'Existing Customer'), ('agent', 'Direct from Agent')], default='agent', help_text='Who is sharing this referral link', max_length=20),
        ),
    ]
