# Generated by Django 5.1.6 on 2025-03-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0003_referrallink_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrallink',
            name='conversions',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='referrallink',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
