# Generated by Django 5.1.6 on 2025-03-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral_system', '0004_referrallink_conversions_referrallink_visits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referrallink',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
